#!/bin/bash

Rscript -e "PhenotypeSimulator::simulatePhenotypes()" \
        --args --NrSamples=500 --NrPhenotypes=15 --tNrSNP=10000 --cNrSNP=30 \
        --SNPfrequencies=0.05,0.1,0.3,0.4 --genVar=0.4 --h2s=0.025 --phi=0.6 \
        --NrConfounders=1,2,1,2 --pIndependentConfounders=0,1,1,0.5 \
        --delta=0.3 --gamma=1 --pcorr=0.8 --NrFixedEffects=4 \
        --directory="./" --subdirectory=genotype_simulation \
        --distConfounders=bin,cat_norm,cat_unif,norm \
        --probConfounders=0.2 --catConfounders=3,4 \
        --seed=20210929 --showProgress --saveTable \
        --savePLINK

Rscript ../_h/simulate_bulk_geneExpression.R
