#!/bin/bash
## Author: Kynon J Benjamin
##
## This script runs conversion to onehot encoding in parallel.
##
## Input: Feature annotation and features to select.
##
## Output: Onehot encoded text file of SNPs for each features.

GENE_BED="../../_h/gene.bed"
FEATURE="../../_h/dRFE_predictive_features.txt.gz"

grep -f <(zcat $FEATURE | cut -f1) $GENE_BED | \
    parallel --jobs 16 bash ../_h/convert2onehot.sh {}
