#!/bin/sh
## Author: Kynon J Benjamin
##
## This script runs random forest with dynamic recusive feature elimination
## in parallel.

echo "Starting... "`date +"%Y-%m-%d at %T"`

mkdir log_files
ls -d ../../_m/ENSG*/ | parallel --jobs 10 bash ../_h/drfe_run_script.sh {}

echo "Ending... "`date +"%Y-%m-%d at %T"`
